/* GENERATED by validation/validation-domain.mjs --record. Do not edit. */
export default {
 "note": "GENERATED by validation/validation-domain.mjs --record. Do not edit.",
 "validation": {
  "cases": [
   {
    "id": "Quad-E",
    "name": "NASA quadrotor, all-electric",
    "source": "validation/nasa-vehicles.js (NASA/TM-20210017971 Table 12)",
    "configType": "multicopter",
    "powertrain": "battery",
    "payload": 544.3,
    "range_km": 138.9,
    "vCruise": 50.42,
    "MTOW": 2939,
    "errorPct": {
     "MTOW": -0.4,
     "empty": -0.3,
     "struct": 8.2
    },
    "errorModel": "nasa-configs.mjs (NASA technology inputs)"
   },
   {
    "id": "SbS-E",
    "name": "NASA side-by-side helicopter, all-electric",
    "source": "validation/nasa-vehicles.js (NASA/TM-20210017971 Table 12)",
    "configType": "sideBySide",
    "powertrain": "battery",
    "payload": 544.3,
    "range_km": 138.9,
    "vCruise": 50.42,
    "MTOW": 2223,
    "errorPct": {
     "MTOW": -11.5,
     "empty": -15,
     "struct": -22.3
    },
    "errorModel": "nasa-configs.mjs (NASA technology inputs)"
   },
   {
    "id": "L+C-E",
    "name": "NASA lift+cruise, all-electric",
    "source": "validation/nasa-vehicles.js (NASA/TM-20210017971 Table 12)",
    "configType": "liftcruise",
    "powertrain": "battery",
    "payload": 544.3,
    "range_km": 138.9,
    "vCruise": 57.62,
    "MTOW": 3724,
    "errorPct": {
     "MTOW": -23.9,
     "empty": -27.9,
     "struct": -25.9
    },
    "errorModel": "nasa-configs.mjs (NASA technology inputs)"
   },
   {
    "id": "nasa-liftcruise-electric",
    "name": "NASA UAM Lift+Cruise (electric)",
    "source": "validation/reference-aircraft.js",
    "configType": "liftcruise",
    "powertrain": "battery",
    "payload": 544,
    "range_km": 139,
    "vCruise": 42.7,
    "MTOW": 4301,
    "errorPct": {
     "MTOW": -26.6
    },
    "errorModel": "validate.mjs, build-up weight model"
   },
   {
    "id": "joby-s4",
    "name": "Joby S4",
    "source": "validation/reference-aircraft.js",
    "configType": "tiltrotor",
    "powertrain": "battery",
    "payload": 453,
    "range_km": 161,
    "vCruise": 89.4,
    "MTOW": 2404,
    "errorPct": {
     "MTOW": -1.9
    },
    "errorModel": "validate.mjs, build-up weight model"
   },
   {
    "id": "archer-midnight",
    "name": "Archer Midnight",
    "source": "validation/reference-aircraft.js",
    "configType": "hybrid",
    "powertrain": "battery",
    "payload": 454,
    "range_km": 100,
    "vCruise": 66.9,
    "MTOW": 3175,
    "errorPct": {
     "MTOW": -9.2
    },
    "errorModel": "validate.mjs, build-up weight model"
   },
   {
    "id": "volocopter-volocity",
    "name": "Volocopter VoloCity",
    "source": "validation/reference-aircraft.js",
    "configType": "multicopter",
    "powertrain": "battery",
    "payload": 200,
    "range_km": 35,
    "vCruise": 27.8,
    "MTOW": 900,
    "errorPct": {
     "MTOW": 3.7
    },
    "errorModel": "validate.mjs, build-up weight model"
   },
   {
    "id": "L+C-TE",
    "name": "NASA lift+cruise, turboelectric (Silva 2018)",
    "source": "validation/nasa-vehicles.js (Silva et al. 2018 Table 3)",
    "configType": "liftcruise",
    "powertrain": "turboelectric",
    "payload": 544.3,
    "range_km": 138.9,
    "vCruise": 62.76,
    "MTOW": 2727,
    "errorPct": {
     "MTOW": -19.1,
     "empty": -28,
     "fuel": -6
    },
    "errorModel": "validation/turboelectric.mjs (NASA technology inputs)"
   }
  ],
  "envelope": {
   "payload": {
    "label": "Payload",
    "unit": "kg",
    "min": 200,
    "max": 544.3
   },
   "range_km": {
    "label": "Mission range",
    "unit": "km",
    "min": 35,
    "max": 161
   },
   "vCruise": {
    "label": "Cruise speed",
    "unit": "m/s",
    "min": 27.8,
    "max": 89.4
   },
   "MTOW": {
    "label": "Take-off mass",
    "unit": "kg",
    "min": 900,
    "max": 4301
   }
  },
  "layouts": {
   "multicopter": [
    "Quad-E",
    "volocopter-volocity"
   ],
   "sideBySide": [
    "SbS-E"
   ],
   "liftcruise": [
    "L+C-E",
    "nasa-liftcruise-electric"
   ],
   "tiltrotor": [
    "joby-s4"
   ],
   "hybrid": [
    "archer-midnight"
   ]
  },
  "byPowertrain": {
   "battery": {
    "envelope": {
     "payload": {
      "label": "Payload",
      "unit": "kg",
      "min": 200,
      "max": 544.3
     },
     "range_km": {
      "label": "Mission range",
      "unit": "km",
      "min": 35,
      "max": 161
     },
     "vCruise": {
      "label": "Cruise speed",
      "unit": "m/s",
      "min": 27.8,
      "max": 89.4
     },
     "MTOW": {
      "label": "Take-off mass",
      "unit": "kg",
      "min": 900,
      "max": 4301
     }
    },
    "layouts": {
     "multicopter": [
      "Quad-E",
      "volocopter-volocity"
     ],
     "sideBySide": [
      "SbS-E"
     ],
     "liftcruise": [
      "L+C-E",
      "nasa-liftcruise-electric"
     ],
     "tiltrotor": [
      "joby-s4"
     ],
     "hybrid": [
      "archer-midnight"
     ]
    },
    "count": 7
   },
   "turboelectric": {
    "envelope": {
     "payload": {
      "label": "Payload",
      "unit": "kg",
      "min": 544.3,
      "max": 544.3
     },
     "range_km": {
      "label": "Mission range",
      "unit": "km",
      "min": 138.9,
      "max": 138.9
     },
     "vCruise": {
      "label": "Cruise speed",
      "unit": "m/s",
      "min": 62.76,
      "max": 62.76
     },
     "MTOW": {
      "label": "Take-off mass",
      "unit": "kg",
      "min": 2727,
      "max": 2727
     }
    },
    "layouts": {
     "liftcruise": [
      "L+C-TE"
     ]
    },
    "count": 1
   }
  },
  "caveat": "A per-variable envelope. Ranges are as each source publishes them; some include a reserve and some do not (see validate.mjs)."
 },
 "verification": {
  "source": "validation/identity-sweep.js (validation/identities.mjs)",
  "layouts": [
   "liftcruise",
   "hybrid",
   "hybridPusher",
   "tiltrotor",
   "multicopter",
   "sideBySide"
  ],
  "sweep": {
   "payload": [
    100,
    900
   ],
   "range": [
    50,
    360
   ],
   "vCruise": [
    30,
    120
   ],
   "cruiseAlt": [
    200,
    3000
   ],
   "LD": [
    5,
    22
   ],
   "AR": [
    4,
    16
   ],
   "clDesign": [
    0.35,
    0.95
   ],
   "taper": [
    0.2,
    0.8
   ],
   "tc": [
    0.08,
    0.2
   ],
   "propDiam": [
    1,
    5
   ],
   "twRatio": [
    1,
    1.6
   ],
   "etaHov": [
    0.4,
    0.85
   ],
   "etaSys": [
    0.5,
    0.95
   ],
   "sedCell": [
    150,
    500
   ],
   "etaBat": [
    0.7,
    0.99
   ],
   "socMin": [
    0.05,
    0.4
   ],
   "ewf": [
    0.3,
    0.7
   ],
   "fusLen": [
    3,
    10
   ],
   "fusDiam": [
    0.8,
    2.5
   ],
   "deltaISA": [
    -15,
    30
   ],
   "vtGamma": [
    20,
    70
   ],
   "vtCh": [
    0.15,
    1
   ],
   "vtCv": [
    0.015,
    0.1
   ],
   "vtAR": [
    1.5,
    4
   ]
  }
 }
};
