/* =====================================================================
   TRANSPORT INPUT SET — a twin-engine jet airliner
   =====================================================================
   Sized by its payload, range, cruise Mach and its take-off and landing
   field lengths, not by hover or stall speed. Defaults describe a
   Boeing 737-800 class aircraft. Status as for the trainer:
     sourced  printed in the cited document
     derived  computed from sourced numbers (working in `source`)
     assumed  a stated judgement with no free source
   Documents: eVTOL_Sizing_Research/classes/transport/sources/.
   ===================================================================== */

const ACAPS = "Boeing D6-58325-6, 737 Airplane Characteristics for Airport Planning (Oct 2005)";
const DECK = "NASA Aviary large_single_aisle_2 FLOPS deck (a 737-800 model; Apache-2.0)";
const SCHOLZ = "Scholz, Aircraft Design lecture notes ch.5 (HAW Hamburg)";
const CFR = "14 CFR";

export const TRANSPORT_INPUTS = Object.freeze({
  /* Mission */
  firstClass:      { value: 12, unit: "", min: 0, max: 60, section: "Mission", label: "First-class passengers", status: "sourced", source: DECK },
  businessClass:   { value: 0, unit: "", min: 0, max: 100, section: "Mission", label: "Business-class passengers", status: "sourced", source: DECK },
  economyClass:    { value: 150, unit: "", min: 0, max: 400, section: "Mission", label: "Economy passengers", status: "sourced", source: `${DECK}; ${ACAPS} p.27 gives 160 two-class / 184` },
  massPerPassenger:{ value: 165, unit: "lb", min: 150, max: 230, section: "Mission", label: "Mass per passenger", status: "sourced", source: "FLOPS, NASA/TM-2017-219627 Eq 128 default" },
  baggagePerPassenger: { value: 35, unit: "lb", min: 0, max: 60, section: "Mission", label: "Baggage per passenger", status: "sourced", source: `${DECK}; FLOPS Eq 129-130 gives 35/40/44 lb by range` },
  cargo:           { value: 4077, unit: "lb", min: 0, max: 40000, section: "Mission", label: "Cargo", status: "sourced", source: DECK },
  designRange:     { value: 2960, unit: "nm", min: 300, max: 8000, section: "Mission", label: "Design range", status: "sourced", source: DECK },
  cruiseMach:      { value: 0.785, unit: "", min: 0.5, max: 0.86, section: "Mission", label: "Cruise Mach number", status: "sourced", source: DECK },
  cruiseAltFt:     { value: 35000, unit: "ft", min: 20000, max: 41000, section: "Mission", label: "Cruise altitude", status: "assumed", source: "Typical single-aisle cruise altitude; the deck's mission altitude is not in the fetched files" },
  maxMach:         { value: 0.82, unit: "", min: 0.6, max: 0.9, section: "Mission", label: "Maximum operating Mach", status: "sourced", source: DECK },
  fuelMethod:      { value: "mission", unit: "", options: ["loftin", "regulatory", "mission"], section: "Mission", label: "Mission fuel method", status: "sourced", source: "loftin: NASA RP-1060 pp.152-153, Breguet at the average cruise L/D with reserves as a range increment, no taxi or climb allowance. regulatory: Scholz Table 5.9 segment fractions (after Roskam) with 14 CFR 121.639 alternate and 45-minute reserve. mission: taxi, take-off, climb and descent integrated as in Drela, TASOPT 2.00 A.2.15, with the NASA Aviary FLOPS engine-deck shape, Breguet cruise, and the reserve policy below" },
  reservePolicy:   { value: "us-domestic", unit: "", options: ["us-domestic", "us-flag", "easa", "nbaa"], section: "Mission", label: "Reserve policy (mission method)", status: "sourced", source: "us-domestic: 14 CFR 121.639 (alternate + 45 min at cruise consumption). us-flag: 121.645(b) (10% of trip time + alternate + 30 min hold at 1,500 ft). easa: EASA AMC/GM Part-CAT (5% contingency + alternate + 30 min hold at 1,500 ft). nbaa: 200 nm alternate + 30 min hold at 5,000 ft (secondary sources only)" },
  climbCasKt:      { value: 290, unit: "kt", min: 200, max: 340, section: "Mission", label: "Climb CAS above 10,000 ft (mission method)", status: "assumed", source: "Typical jet-transport schedule; below 10,000 ft the 250 kt limit of 14 CFR 91.117(a) applies" },
  descentCasKt:    { value: 290, unit: "kt", min: 200, max: 340, section: "Mission", label: "Descent CAS above 10,000 ft (mission method)", status: "assumed", source: "As the climb CAS" },
  climbThrottle:   { value: 0.95, unit: "", min: 0.6, max: 1, section: "Mission", label: "Climb thrust / maximum thrust (mission method)", status: "assumed", source: "No public climb rating; the NASA Aviary FLOPS deck gives maximum thrust only" },
  taxiMin:         { value: 10.06, unit: "min", min: 0, max: 40, section: "Mission", label: "Taxi-out time (mission method)", status: "sourced", source: "NASA Aviary large_single_aisle_1 GASP deck: mission:taxi:duration 0.1677 h" },
  takeoffFuelFraction: { value: 0.00378, unit: "", min: 0, max: 0.02, section: "Mission", label: "Take-off fuel / gross weight (mission method)", status: "derived", source: "NASA Aviary large_single_aisle_2 FLOPS deck: mission:takeoff:fuel_mass 659 lb at 174,200 lb" },
  alternateAltFt:  { value: 25000, unit: "ft", min: 5000, max: 41000, section: "Mission", label: "Cruise altitude to the alternate (mission method)", status: "assumed", source: "No rule; lower than the main cruise, as short diversions are flown" },
  alternateMach:   { value: 0.7, unit: "", min: 0.4, max: 0.85, section: "Mission", label: "Cruise Mach to the alternate (mission method)", status: "assumed", source: "No rule" },
  reserveIncrementNm: { value: 500, unit: "nm", min: 0, max: 1200, section: "Mission", label: "Reserve range increment (Loftin method)", status: "sourced", source: 'Loftin, NASA RP-1060 p.153: "an increment of 400 to 600 miles to the design range" (midpoint; read as nautical miles, the unit the chapter uses for jets)' },
  alternateNm:     { value: 200, unit: "nm", min: 0, max: 500, section: "Mission", label: "Distance to alternate", status: "sourced", source: "Study practice, NASA CR-2011-216847 (SUGAR) p.101; the rule (14 CFR 121.639(b)) requires an alternate but no distance" },
  reserveMin:      { value: 45, unit: "min", min: 0, max: 90, section: "Mission", label: "Final reserve at cruise consumption", status: "sourced", source: `${CFR} 121.639(c): "to fly for 45 minutes at normal cruising fuel consumption"` },

  /* Field and climb requirements */
  landingFieldLengthM: { value: 1650, unit: "m", min: 900, max: 3500, section: "Requirements", label: "Landing field length (dry, sea level)", status: "sourced", source: `${ACAPS} §3.4.30: flaps 40, dry, sea level, 146,300 lb ≈ 5,410 ft (read from the chart)` },
  takeoffFieldLengthM: { value: 2195, unit: "m", min: 1000, max: 4000, section: "Requirements", label: "Take-off field length (dry, sea level, ISA)", status: "sourced", source: `${ACAPS} §3.3.95: CFM56-7B27, 174,200 lb ≈ 7,200 ft (read from the chart)` },
  landingToTakeoffMass: { value: 0.84, unit: "", min: 0.6, max: 1.0, section: "Requirements", label: "Maximum landing / take-off mass", status: "derived", source: `${ACAPS} p.27: 146,300 / 174,200 lb; ${SCHOLZ} Table 5.3 gives 0.89 for 1,000-3,000 nm` },
  takeoffMethod:   { value: "loftin", unit: "", options: ["loftin", "far25"], section: "Requirements", label: "Take-off field length method", status: "sourced", source: `loftin: ${SCHOLZ} (5.10), a statistical line fitted to a fleet. far25: the distances 14 CFR 25.109(a) and 25.113(a) define, integrated along the run, with the balanced V1 at which the accelerate-stop and take-off distances are equal. The rule defines the distances but not the aeroplane, so the speed schedule, ground lift, friction coefficients and rotation time below are all assumed; see src/classes/transport/takeoff.js` },
  vrOverVs:        { value: 1.10, unit: "", min: 1.0, max: 1.3, section: "Requirements", label: "Rotation speed / stall speed (far25 method)", status: "assumed", source: `${CFR} 25.107(e)(1) requires VR to be at least V1, at least 1.05 VMC and fast enough to reach V2 by 35 ft, but gives no value. 1.10 is a conventional transport schedule` },
  vlofOverVs:      { value: 1.12, unit: "", min: 1.0, max: 1.4, section: "Requirements", label: "Lift-off speed / stall speed (far25 method)", status: "assumed", source: `${CFR} 25.107(f) defines VLOF as the speed at which the airplane first becomes airborne and bounds it against VMU, but gives no value` },
  v2OverVs:        { value: 1.13, unit: "", min: 1.05, max: 1.4, section: "Requirements", label: "Take-off safety speed / stall speed (far25 method)", status: "sourced", source: `${CFR} 25.107(b)(1): V2MIN may not be less than 1.13 VSR for turbine aeroplanes of more than two engines that are turbopropeller powered, and for turbojets. This is the regulatory floor, taken as the schedule` },
  clGroundRoll:    { value: 0.20, unit: "", min: 0, max: 1.0, section: "Requirements", label: "Lift coefficient during the ground roll (far25 method)", status: "assumed", source: "The wing at ground attitude with take-off flap. No public value for a generic transport; it matters mainly through the lift it takes off the wheels during braking" },
  muRolling:       { value: 0.02, unit: "", min: 0.01, max: 0.05, section: "Requirements", label: "Rolling friction coefficient (far25 method)", status: "sourced", source: "Lucht (HAW bachelor thesis, Numerical and analytical take-off field length) Table 5.2: 0.02 for a dry paved runway, the value the textbooks agree on" },
  muBraking:       { value: 0.40, unit: "", min: 0.15, max: 0.6, section: "Requirements", label: "Braking friction coefficient, dry (far25 method)", status: "assumed", source: "Dry paved runway with anti-skid. 14 CFR 25.109(c)-(d) prescribes wet-runway friction as a function of ground speed but leaves the dry value to be demonstrated" },
  brakeTransitionS: { value: 2.0, unit: "s", min: 0, max: 5, section: "Requirements", label: "First action to fully developed braking (far25 method)", status: "assumed", source: `${CFR} 25.109(a)(1)(ii) has the aeroplane accelerate "to the highest speed reached during the rejected takeoff" after the pilot's first action at V1, and (a)(1)(iii) stops it from that speed, not from V1. The rule does not say how long the interval is - it is demonstrated by the applicant. Over it the engines spool down, the spoilers deploy and the brakes build. It is separate from, and additional to, the two seconds at V1 that (a)(1)(iv) adds to the distance` },
  brakedWeightFraction: { value: 0.92, unit: "", min: 0.6, max: 1.0, section: "Requirements", label: "Share of the normal load on braked wheels (far25 method)", status: "assumed", source: `${CFR} 25.109(b)(2)(ii) requires "the distribution of the normal load between braked and unbraked wheels at the most adverse center-of-gravity position" to be taken into account: the nose gear carries part of the weight and has no brakes, so only part of the normal force becomes retarding force. The rule gives no value; 0.92 is a conventional main-gear share for a tricycle transport` },
  rotationTimeS:   { value: 1.0, unit: "s", min: 0, max: 5, section: "Requirements", label: "Rotation time (far25 method)", status: "assumed", source: "The interval from VR to lift-off, flown at about VR. One second is the conventional transport value; no regulation sets it" },
  recognitionTimeS: { value: 1.0, unit: "s", min: 0, max: 3, section: "Requirements", label: "Engine-failure recognition time (far25 method)", status: "sourced", source: `${CFR} 25.107(a)(2): V1 may not be less than VEF plus the speed gained between the engine failing and the pilot's first action to stop. The demonstrated interval is the applicant's; one second is the conventional value, and it is separate from the two seconds 25.109(a)(1)(iv) adds to the distance` },
  mzfwRatio:       { value: 0.7939, unit: "", min: 0.5, max: 1.0, section: "Requirements", label: "Maximum zero-fuel / take-off mass", status: "sourced", source: `${ACAPS} p.27: MZFW 138,300 lb over MTOW 174,200 lb. It sets the maximum payload (MZFW − OEW) and so the corner of the payload-range diagram. Across the 921 dataset rows that publish both, the ratio runs 0.56 to 0.97 with a median of 0.78` },
  icaRequirement:  { value: "cruise-altitude", unit: "", options: ["cruise-altitude", "explicit", "off"], section: "Requirements", label: "Initial cruise altitude requirement", status: "sourced", source: `cruise-altitude: the aircraft must be able to reach the altitude it is said to cruise at, with the residual rate of climb below. explicit: use the altitude entered below instead. off: not checked, which lets a design be sized that cannot reach its own cruise altitude. Every public study process applies this check - NASA/CR-2011-216847 (SUGAR) Table 5.3 p.46, Douglas at 31,000 ft, Lockheed at 30,000 ft, and Airbus's maximum recommended altitude (Getting to Grips with Aircraft Performance p.138). Measured over the 168-aircraft dataset it improves both take-off methods: the statistical line goes from a mean take-off-mass error of -0.7 % and 9.2 % absolute to -0.0 % and 8.8 %, with 87 aircraft within 5 % rather than 73` },
  initialCruiseAltReqFt: { value: 35000, unit: "ft", min: 0, max: 45000, section: "Requirements", label: "Initial cruise altitude required (explicit requirement)", status: "sourced", source: "NASA/CR-2011-216847 (SUGAR) Table 5.3 p.46 carries an initial-cruise-altitude requirement with a residual rate of climb, and Table 6.2 p.104 reports a thrust and a buffet ICAC; Douglas sized engines to a 31,000 ft initial cruise altitude (NASA CR p.30) and Lockheed required at least 30,000 ft. The tool's cruise line asks only that thrust equal drag, which is a zero-rate ceiling, so without this an aircraft can be sized that cannot reach the altitude it is said to cruise at. 0 leaves the check off" },
  icaResidualRocFpm: { value: 300, unit: "ft/min", min: 0, max: 1000, section: "Requirements", label: "Residual rate of climb at the initial cruise altitude", status: "sourced", source: "NASA/CR-2011-216847 (SUGAR) Table 5.3 p.46: \"ROC at ICA (fpm): 300\". Airbus uses the same 300 ft/min climb ceiling in its definition of the maximum recommended altitude (Getting to Grips with Aircraft Performance p.138)" },
  buffetClLimit:   { value: 0, unit: "", min: 0, max: 1.5, section: "Requirements", label: "Buffet-limited lift coefficient at cruise Mach (0 = not checked)", status: "assumed", source: "NOT A SOURCED DEFAULT. Airbus includes the 1.3 g buffet boundary in the maximum recommended altitude (p.138, 145, 155) and AC 25-7D §10.1.2.4 calls the 0.3 g margin \"practical operating criteria imposed by most operators\", but no verified public CL_buffet(M) correlation was found: the FLOPS BUFFET table needs its reference CL and unit construct settled first, and the Airbus A320 FCOM chart is an image. Enter the buffet CL for this wing at the cruise Mach and the check applies 1.3 x CL(1 g) <= this; left at 0 nothing is checked and the omission is stated in the warnings" },
  fieldElevationFt: { value: 0, unit: "ft", min: -1000, max: 14000, section: "Requirements", label: "Field elevation the field lengths are quoted at", status: "sourced", source: `${ACAPS} §3.3.95 and §3.4.30 quote the 737-800's field lengths at sea level. Scholz (5.5) and (5.10) carry the density ratio σ, which this and the temperature offset below set` },
  fieldDeltaIsaC:  { value: 0, unit: "°C", min: -30, max: 40, section: "Requirements", label: "Temperature above ISA the field lengths are quoted at", status: "sourced", source: `${ACAPS}: standard day. Boeing sizes take-off field length at 86 °F (ISA+15 at sea level), NASA/CR-2011-216847 (SUGAR) p.98, p.103; enter 15 to size to that day` },
  kLanding:        { value: 0.107, unit: "kg/m³", min: 0.07, max: 0.15, section: "Requirements", label: "Loftin landing constant k_L", status: "sourced", source: `${SCHOLZ} (5.5), after Loftin (NASA RP-1060 ch.3): 0.107 kg/m³ for jet transports. The business-jet class uses 0.091 (classes/business-jet/METHODS.md §8.4). MATCHED PAIR — DO NOT CHANGE ONE WITHOUT THE OTHER. The landing line is W/S = k_L x sigma x CLmax,L x s_LFL, so only the PRODUCT k_L x CLmax,L is fitted, and Loftin fitted it as a regression of field length on approach speed squared with the OLD 1/1.69 speed convention baked in (NASA RP-1060 p.106). Here 0.107 x 3.0 = 0.321. The 737-800's PHYSICAL 1-g CLmax, from its published 144 kt approach speed at maximum landing weight via 25.125's V_REF >= 1.23 V_SR0, is 2.35 - and 0.137 x 2.35 = 0.322, the same product. So substituting a physically computed CLmax while leaving k_L alone does not improve the model, it inflates the wing by 28 %. If a high-lift module ever computes CLmax, k_L must be re-fitted in the same commit. eVTOL_Sizing_Research/classes/cross-class/HIGH-LIFT.md section 1.` },
  kTakeoff:        { value: 2.34, unit: "m³/kg", min: 1.8, max: 3.2, section: "Requirements", label: "Loftin take-off constant k_TO", status: "sourced", source: `${SCHOLZ} (5.10), after Loftin: 2.34 m³/kg for jet transports. The business-jet class uses 2.64 (classes/business-jet/METHODS.md §8.4)` },
  landingMethod:   { value: "far25", unit: "", options: ["loftin", "far25"], section: "Requirements", label: "Landing field length method", status: "sourced", source: `loftin: the fitted line m_ML/S = k_L x sigma x CLmax,L x s_LFL, ${SCHOLZ} (5.5) after Loftin. far25: the landing distance COMPUTED from 14 CFR 25.125 - V_REF = 1.23 V_SR0, an energy air distance from the 50 ft screen, an integrated braked ground roll, and the 121.195(b) 60 % despatch factor. The computed method removes k_L from the landing constraint entirely, which is what lets CLmax become a physical lift coefficient instead of half of a fitted pair. MEASURE BEFORE SWITCHING: see eVTOL_Sizing_Research/classes/cross-class/HIGH-LIFT.md section 7` },
  landingSpoilers: { value: true, unit: "", section: "Requirements", label: "Spoilers dump lift on touchdown (far25 landing)", status: "assumed", source: "On landing the ground spoilers deploy and destroy lift, which is what puts the weight on the wheels for braking - it is the one thing that is unambiguously different between a landing roll and a rejected take-off roll, where the take-off model's ground-run lift coefficient still applies. Setting the ground lift coefficient to zero is what a lift dumper does. 14 CFR 25.459 requires spoiler LOADS to be determined from test data, and no public source gives the residual lift coefficient with them deployed, so this is a physical argument rather than a measured value" },
  landingFreeRollS: { value: 2.0, unit: "s", min: 0, max: 5, section: "Requirements", label: "Touchdown to fully developed braking (far25 landing)", status: "assumed", source: "Deliberately left at the rejected take-off's brake transition time rather than shortened to fit. A certified landing has no V1 recognition decision, so the real delay is probably shorter, but 25.125 leaves it to the applicant and no public value was found. Shortening it to 1.0 s alone moves the 737-800 field length from +21 % to +15 %, which is why it is an input and not a constant" },
  landingMuBraking: { value: 0.50, unit: "", min: 0.15, max: 0.7, section: "Requirements", label: "Braking friction, landing (far25 landing)", status: "derived", source: "CALIBRATED ON THE FLEET, and this is the one fitted number left in the landing constraint. Swept over the 168-aircraft validation record at 0.40/0.45/0.50/0.544/0.60/0.65, the take-off-mass error is 10.0/9.6/9.6/9.9/10.8/11.7 % and 0.50 is the best. Note it is NOT the 0.544 that reproduces the 737-800's own published field length exactly - fitting one aeroplane and fitting the fleet disagree, and the fleet wins. It is high for a dry-runway friction coefficient because it absorbs what the model omits: reverse thrust, the real spoiler drag, and any braking the 2 s free roll over-charges. That is the same kind of absorption k_L did, with two differences - it is ONE parameter inside an explicit physical model rather than a lumped constant, and the speeds, distances and CLmax around it are all real" },
  vTouchdownOverVref: { value: 0.95, unit: "", min: 0.88, max: 1.0, section: "Requirements", label: "Touchdown speed / V_REF (far25 landing)", status: "assumed", source: "No public source. 25.125 requires a stabilised approach at not less than V_REF to the 50 ft point and says nothing about the touchdown speed" },
  clMaxLanding:    { value: 2.35, unit: "", min: 1.8, max: 3.4, section: "Requirements", label: "CLmax, landing", status: "derived", source: `A PHYSICAL LIFT COEFFICIENT, at last. 2.35 is the 737-800's own 1-g CLmax, backed out of its published 144 kt approach speed at maximum landing weight through 25.125(b)(2)(i)(A)'s V_REF >= 1.23 V_SR0. Four modern transports measured the same way give 2.35 (737-800), 2.66 (A320), 2.63 (ATR 72-600) and 2.60 (Q400), and Loftin's own 18-aircraft fleet statistic is 2.54. This became usable only when the landing line stopped being Loftin's fitted correlation: while k_L = 0.107 was in the constraint, CLmax was half of a fitted PAIR and had to carry the value 3.0 that the pair demanded - the Aviary deck's round integer, which that deck disclaims in its own comments ("# TODO investigate the origin of these values"). Setting 2.35 while k_L is still 0.107 inflates the wing 30 %; the far25 method removes k_L entirely, which is what makes this legal. eVTOL_Sizing_Research/classes/cross-class/HIGH-LIFT.md section 7. HISTORICAL NOTE ON THE OLD VALUE: ${DECK} sets Mission.Landing.LIFT_COEFFICIENT_MAX to the round integer 3 under two comments of its own: "# TODO investigate the origin of these values (taken from benchmark tests)" and "# TODO: should this come from aero?". Four modern transports measured from published approach speeds give 2.35 (737-800), 2.66 (A320), 2.63 (ATR 72-600) and 2.60 (Q400), and Loftin's own 18-aircraft fleet statistic is 2.54 - nothing is near 3.0. ${SCHOLZ} Table 5.1 gives 1.8-2.8. If the landing method is switched back to "loftin", k_L must move with this value or the wing is wrong: the pair that reproduces the old behaviour is k_L 0.137 with CLmax 2.35, whose product 0.322 matches the old 0.107 x 3.0 = 0.321 and measures the same on the fleet` },
  clMaxTakeoff:    { value: 2.0, unit: "", min: 1.4, max: 2.6, section: "Requirements", label: "CLmax, take-off", status: "assumed", source: `As clMaxLanding: ${DECK} sets Mission.Takeoff.LIFT_COEFFICIENT_MAX to the round integer 2 under its own "# TODO: should this come from aero?". ${SCHOLZ} Table 5.1 gives 1.6-2.2. Matched with k_TO = 2.34 the same way the landing pair is matched` },
  engineLocation:  { value: "wing", unit: "", options: ["wing", "aft-fuselage", "wing+tail", "fuselage-3"], section: "Requirements", label: "Engine location", status: "sourced", source: "FLOPS NEW/NEF (NASA/TM-2017-219627 Eq 38, 56, 102, 104); aft nacelle drag NASA TN D-3781 p.3; wing+tail and fuselage-3 are three-engine layouts. The 737-800 has wing engines (Boeing D6-58325-6)" },
  tailSizing:      { value: "ratio", unit: "", options: ["ratio", "volume"], section: "Wing", label: "Tail sizing", status: "sourced", source: "ratio: tail areas as fixed fractions of wing area (below). volume: Scholz 2021 (INCAS 13(3)) tail volume coefficients (Table 2) and lever arms (Eq 3-4)" },
  tailCategory:    { value: "jet-transport", unit: "", options: ["jet-transport", "business-jet"], section: "Wing", label: "Tail volume class (volume sizing)", status: "sourced", source: "Scholz 2021 Table 2: jet transport C_H 0.991, C_V 0.0793; business jets 0.694, 0.0722" },
  tTail:           { value: false, unit: "", section: "Wing", label: "T-tail (volume coefficients -4%)", status: "sourced", source: "Scholz 2021 p.155: \"For T-tails the given tail volume coefficients may be reduced by 4%\". The 737-800 has a conventional tail" },
  numEngines:      { value: 2, unit: "", min: 2, max: 4, section: "Requirements", label: "Engines (on the wing)", status: "sourced", source: ACAPS },

  /* Wing */
  wingAspectRatio: { value: 9.45, unit: "", min: 6, max: 13, section: "Wing", label: "Aspect ratio", status: "sourced", source: DECK },
  wingSweep:       { value: 25.03, unit: "deg", min: 0, max: 40, section: "Wing", label: "Quarter-chord sweep", status: "sourced", source: DECK },
  wingTaper:       { value: 0.2373, unit: "", min: 0.15, max: 0.6, section: "Wing", label: "Taper ratio", status: "sourced", source: DECK },
  wingTc:          { value: 0.1317, unit: "", min: 0.08, max: 0.18, section: "Wing", label: "Thickness ratio", status: "sourced", source: DECK },
  wingCompositeFraction: { value: 0, unit: "", min: 0, max: 1, section: "Wing", label: "Wing composite fraction (FLOPS FCOMP)", status: "sourced", source: "FLOPS (NASA/TM-2017-219627) Eq 33, 35, 36: bending ×(1 − 0.4 FCOMP), shear and control ×(1 − 0.17 FCOMP), miscellaneous ×(1 − 0.3 FCOMP); the wing is the only group FLOPS reduces for composites. 0 for the 737-800's aluminium wing. Use 1 for a carbon-fibre wing box: FCOMP is a utilisation level, not a mass fraction, so a 787 wing is not 0.5 because the aircraft is 50 % composite by structural weight, and NASA applies 1 for \"maximum use of composites\" (Berton, NASA/TM-20220015470 §3). Measured here: the four A350 rows of the dataset size +20.0 % heavy at 0, +14.6 % at 0.5 and +9.7 % at 1. FLOPS has no composite term outside the wing, so a composite fuselage and tail are still modelled as metal and the aircraft stays heavy. The 787 and A350 have composite wings (Boeing AERO Q4 2006; Airbus ICAS 2016); eVTOL_Sizing_Research/classes/cross-class/COMPOSITES.md" },
  wingFuelFraction:{ value: 0.7752, unit: "", min: 0.3, max: 0.95, section: "Wing", label: "Wing volume usable for fuel", status: "sourced", source: DECK },
  htAreaRatio:     { value: 0.3038, unit: "", min: 0.15, max: 0.5, section: "Wing", label: "Horizontal tail / wing area", status: "derived", source: `${DECK}: 407.3 / 1,341 ft²` },
  vtAreaRatio:     { value: 0.2122, unit: "", min: 0.1, max: 0.35, section: "Wing", label: "Vertical tail / wing area", status: "derived", source: `${DECK}: 284.5 / 1,341 ft²` },

  /* Aerodynamics */
  cfEquivalent:    { value: 0.003, unit: "", min: 0.002, max: 0.005, section: "Aerodynamics", label: "Equivalent skin friction", status: "sourced", source: `${SCHOLZ} p.5-21: "0.003 is a common value in literature for jet transports"` },
  oswaldCruise:    { value: 0.85, unit: "", min: 0.6, max: 0.95, section: "Aerodynamics", label: "Oswald factor, cruise", status: "sourced", source: `${SCHOLZ} p.5-21: Loftin 1980 uses 0.85 for jets in cruise` },
  oswaldFlaps:     { value: 0.7, unit: "", min: 0.5, max: 0.9, section: "Aerodynamics", label: "Oswald factor, flaps down", status: "sourced", source: `${SCHOLZ} p.5-13, after Loftin` },
  dragMethod:      { value: "equivalent-cf", unit: "", options: ["equivalent-cf", "flops"], section: "Aerodynamics", label: "Cruise drag method", status: "sourced", source: "equivalent-cf: CD0 = c_f,eq · S_wet/S with the Oswald factor below (Scholz ch.5, after Loftin). flops: the FLOPS drag build-up as NASA Aviary implements it (skin friction and form factor per component, compressibility and Delta-Method lift-dependent drag tables), reproducing FLOPS polars of three transports (validation/transport-aero.mjs)" },
  airfoilTech:     { value: 1.87, unit: "", min: 1, max: 2, section: "Aerodynamics", label: "Airfoil technology, 1 conventional to 2 supercritical (FLOPS drag)", status: "sourced", source: `${DECK} (FLOPS AITEK); FLOPS default 1` },
  wingCamber:      { value: 0.015, unit: "% chord", min: 0, max: 5, section: "Aerodynamics", label: "Maximum camber at 70% semispan (FLOPS drag)", status: "sourced", source: `${DECK} (FLOPS CAM); FLOPS default 0` },
  spanEfficiencyFlops: { value: 1.35, unit: "", min: 0, max: 2, section: "Aerodynamics", label: "Span efficiency input E (FLOPS drag; 0.3 or less adds to 1)", status: "sourced", source: `${DECK} (FLOPS E); FLOPS default 1. FLOPS adds Delta-Method pressure drag to CL²/(πAe) separately` },
  cd0Clean:        { value: 0.02, unit: "", min: 0.012, max: 0.03, section: "Aerodynamics", label: "CD0 for the climb checks", status: "sourced", source: `${SCHOLZ} p.5-13, after Loftin` },

  /* Propulsion */
  tsfcCruise:      { value: 0.60, unit: "lb/lbf/h", min: 0.45, max: 0.9, section: "Propulsion", label: "Cruise TSFC (M 0.8, 35,000 ft)", status: "derived", source: "CFM56-7B27 at M 0.80, 35,000 ft: 0.600 (Jenkinson companion Data B and the Hammami database, secondary compilations; eVTOL_Sizing_Research/datasets/engines/cruise-tsfc/FINDINGS.md). No free primary source gives cruise TSFC. The Loftin method was tuned with 0.66 (Aviary turbofan_24k_1 deck near cruise T4)" },
  bypassRatio:     { value: 5.1, unit: "", min: 0, max: 12, section: "Propulsion", label: "Bypass ratio", status: "derived", source: "CFM56-7B27: 5.1 (same compilations as the cruise TSFC)" },
  thrustLapseMethod: { value: "deck", unit: "", options: ["scholz", "deck"], section: "Propulsion", label: "Cruise thrust lapse", status: "sourced", source: `scholz: ${SCHOLZ} (5.29), a correlation on bypass ratio and altitude, giving 0.233 of static thrust at 35,000 ft for a bypass ratio of 5.1. deck: the maximum thrust of the ${DECK} at the cruise Mach and altitude, which gives 0.186 there — 25 % apart. The mission has always used the deck, so "deck" makes the matching chart and the mission agree, which is how Boeing describes its own process (NASA/CR-2011-216847 p.46, p.98, Fig 6.1). The correlation is kept because it carries bypass ratio explicitly, where the deck is one engine's shape` },
  cruiseRatingFraction: { value: 1.0, unit: "", min: 0.5, max: 1.0, section: "Propulsion", label: "Cruise rating / maximum thrust (deck lapse)", status: "assumed", source: "No public split between maximum, climb and cruise ratings was found; Airbus states only that the climb rating exceeds the cruise rating (Getting to Grips with Aircraft Performance p.42). At 1 the cruise line asks that maximum thrust available covers cruise drag" },
  engineRefThrust: { value: 27301, unit: "lbf", min: 5000, max: 120000, section: "Propulsion", label: "Reference engine SLS thrust", status: "sourced", source: `${DECK}; ${ACAPS}: CFM56-7B27 at 27,300 lb` },
  engineRefMass:   { value: 8071.35, unit: "lb", min: 1000, max: 20000, section: "Propulsion", label: "Reference engine mass", status: "sourced", source: DECK },
  engineMassExponent: { value: 1.15, unit: "", min: 0.3, max: 2, section: "Propulsion", label: "Engine mass-thrust exponent", status: "sourced", source: "FLOPS Eq 75 default EEXP 1.15" },
  nacelleRefDiameter: { value: 7.0, unit: "ft", min: 3, max: 15, section: "Propulsion", label: "Reference nacelle diameter", status: "sourced", source: DECK },
  nacelleRefLength:{ value: 11.65, unit: "ft", min: 5, max: 25, section: "Propulsion", label: "Reference nacelle length", status: "sourced", source: DECK },
  fuelDensity:     { value: 6.7, unit: "lb/US gal", min: 6.0, max: 7.0, section: "Propulsion", label: "Fuel density", status: "sourced", source: `${ACAPS} p.27: 6,875 US gal = 46,063 lb` },
  fuelVolumeConstraint: { value: false, unit: "", section: "Propulsion", label: "Grow the wing until its tanks hold the mission", status: "sourced", source: "FLOPS and NASA Aviary carry fuel capacity as a sizing constraint (excess fuel capacity ≥ 0), and Boeing's process sizes to a fuel capacity requirement (NASA/CR-2011-216847 p.104, \"FUEL CAPACITY REQ\"). Off by default, because the landing field length sets the wing loading for most airliners and the tanks then hold the mission anyway; when they do not, the result is otherwise an aircraft whose tanks cannot hold its own fuel. Turning it on lowers the wing loading below the landing limit, which is allowed — the landing line is an upper bound" },
  fuselageFuelLb:  { value: 0, unit: "lb", min: 0, max: 200000, section: "Propulsion", label: "Fuel carried outside the wing", status: "assumed", source: "Centre-section and fuselage tankage, which the FLOPS wing-volume estimate does not include. 0 for the 737-800, whose quoted capacity the wing estimate already covers. Business jets and long-range types carry a substantial fuselage load" },
  fuelTanks:       { value: 7, unit: "", min: 1, max: 20, section: "Propulsion", label: "Fuel tanks", status: "sourced", source: DECK },

  /* Fuselage */
  fuselageLength:  { value: 124.75, unit: "ft", min: 60, max: 250, section: "Fuselage", label: "Fuselage length", status: "sourced", source: DECK },
  fuselageWidth:   { value: 12.33, unit: "ft", min: 8, max: 22, section: "Fuselage", label: "Fuselage width", status: "sourced", source: DECK },
  fuselageHeight:  { value: 13.0208, unit: "ft", min: 8, max: 25, section: "Fuselage", label: "Fuselage height", status: "sourced", source: DECK },
  passengerCompartmentLength: { value: 98.5, unit: "ft", min: 30, max: 220, section: "Fuselage", label: "Passenger compartment length", status: "sourced", source: DECK },

  /* Crew and structure */
  flightCrew:      { value: 2, unit: "", min: 2, max: 4, section: "Crew and structure", label: "Flight crew", status: "sourced", source: DECK },
  flightAttendants:{ value: 5, unit: "", min: 0, max: 20, section: "Crew and structure", label: "Flight attendants", status: "sourced", source: `${DECK} (FLOPS Eq 116 by ceiling gives 5, Aviary's floor gives 4; see METHODS.md §5.9)` },
  galleyCrew:      { value: 1, unit: "", min: 0, max: 5, section: "Crew and structure", label: "Galley crew", status: "sourced", source: DECK },
  ultimateLoadFactor: { value: 3.75, unit: "g", min: 3.75, max: 6, section: "Crew and structure", label: "Ultimate load factor (entered)", status: "sourced", source: `${CFR} 25.337(b): limit 2.5 for large transports × 1.5; FLOPS default 3.75` },
  loadFactorMethod: { value: "input", unit: "", options: ["input", "far25"], section: "Crew and structure", label: "Ultimate load factor method", status: "sourced", source: `input: use the entered value. far25: ${CFR} 25.337(b), n = 2.1 + 24,000/(W + 10,000) with W the design gross weight in lb, bounded to 2.5 ≤ n ≤ 3.8, times the 1.5 factor of ${CFR} 25.303. The two agree above about 50,000 lb, where the limit factor is at its 2.5 floor; below it the rule asks for more` },
  mainGearOleoIn:  { value: 84, unit: "in", min: 20, max: 150, section: "Crew and structure", label: "Main gear oleo length", status: "sourced", source: DECK },
  noseGearOleoIn:  { value: 58.8, unit: "in", min: 10, max: 120, section: "Crew and structure", label: "Nose gear oleo length", status: "sourced", source: DECK },
  emptyMarginFraction: { value: 0.00514, unit: "", min: 0, max: 0.1, section: "Crew and structure", label: "Empty-weight margin", status: "sourced", source: DECK },
  paintPerArea:    { value: 0.07, unit: "lb/ft²", min: 0, max: 0.2, section: "Crew and structure", label: "Paint per wetted area", status: "sourced", source: DECK },
  hydraulicPressure: { value: 3000, unit: "psi", min: 1000, max: 5000, section: "Crew and structure", label: "Hydraulic pressure", status: "sourced", source: "FLOPS Eq 104 default" },
});

export const TRANSPORT_DEFAULTS = Object.freeze(
  Object.fromEntries(Object.entries(TRANSPORT_INPUTS).map(([k, v]) => [k, v.value])));
