"""
Extract NASA RAVEN's ACTUAL body cross-sections into src/data/raven-profiles.js.

WHY THIS EXISTS. geometry.js lofted every body from hand-written station
tables of near-circular sections, and the result did not look like an
aircraft. The reason was not the station fractions, which had been measured
carefully; it was the SECTION SHAPE. RAVEN's fuselage is a RoundedRect —
a rounded rectangle with per-corner radii — and it is TALL: height over
width runs 0.75 at the nose to 1.69 at the cabin. Lofting ellipses through
correct stations still produces a torpedo.

An earlier attempt to read these concluded "the fuselage uses general edit
curves and is not reducible to a station table". That was wrong, and it was
wrong for a mechanical reason worth recording: the regex used to pull
<XSecCurve> blocks was non-greedy and the file nests a parm group of the
SAME NAME inside each one, so every match ended at the inner closing tag and
returned a block with no shape parameters in it. The parse below is
depth-aware.

Run from the directory holding the unzipped releases:
    python tools/extract-raven-profiles.py > src/data/raven-profiles.js
"""
import re, glob, os, sys

FT, IN = 0.3048, 0.0254
UNITS = {"RAVEN_v01_003_Release.vsp3": FT,
         "RAVEN SWFT VSP Public Release.vsp3": FT,
         "BD-6_v03_004.vsp3": IN}

def blocks(s, tag):
    """Inner text of each TOP-LEVEL <tag>...</tag>, ignoring nested ones."""
    out, d, st = [], 0, None
    for m in re.finditer(r'</?' + tag + r'>', s):
        if m.group(0) == '<' + tag + '>':
            if d == 0: st = m.end()
            d += 1
        else:
            d -= 1
            if d == 0: out.append(s[st:m.start()])
    return out

def val(b, k):
    m = re.search(r'<' + k + r' Value="([-0-9.eE+]+)"', b)
    return float(m.group(1)) if m else None

def sections(geom, k):
    """Per-station shape: t, vertical offset, width, height, corner radius."""
    rows = []
    for b in blocks(geom, 'XSec'):
        if 'XLocPercent' not in b: continue
        w = val(b, 'RoundedRect_Width')
        h = val(b, 'RoundedRect_Height')
        r = val(b, 'RoundRectXSec_Radius') or 0.0
        if w is None:
            w = val(b, 'Ellipse_Width'); h = val(b, 'Ellipse_Height'); r = None
        if w is None:
            d = val(b, 'Circle_Diameter')
            if d is not None: w = h = d; r = None
        if w is None: continue
        rows.append(dict(t=val(b, 'XLocPercent'), dz=val(b, 'ZLocPercent') or 0.0,
                         w=w * k, h=h * k, r=(r * k if r else 0.0),
                         rounded=val(b, 'RoundedRect_Width') is not None))
    return rows

def emit(name, rows, L):
    """Normalise on MAX WIDTH so the profile is a shape, not a size."""
    wmax = max((x['w'] for x in rows), default=0) or 1.0
    print(f"  {name}: {{")
    print(f"    lengthM: {L:.4f}, maxWidthM: {wmax:.4f}, finenessLoverW: {L/wmax:.4f},")
    print(f"    stations: [")
    for x in rows:
        print(f"      {{ t: {x['t']:.6f}, dz: {x['dz']:.6f}, "
              f"w: {x['w']/wmax:.6f}, h: {x['h']/wmax:.6f}, "
              f"r: {(x['r']/x['w'] if x['w'] else 0):.6f}, rounded: {str(x['rounded']).lower()} }},")
    print("    ],")
    print("  },")

files = sorted(glob.glob("*/*.vsp3"))
if not files:
    sys.exit("no .vsp3 found; run from the directory holding the unzipped releases")

print("/* GENERATED by tools/extract-raven-profiles.py — DO NOT HAND-EDIT.")
print("   NASA RAVEN body cross-sections, normalised on each body's own maximum")
print("   width so they are SHAPES, not sizes. `w`/`h`/`r` are fractions of that")
print("   width; `t` is x/length; `dz` is the section's vertical offset as a")
print("   fraction of length (which is how OpenVSP stores ZLocPercent).")
print("   `rounded` marks a RoundedRect section — RAVEN's fuselage is one, and")
print("   lofting it as an ellipse is what made every body read as a torpedo. */")
print("export const RAVEN_PROFILES = {")
for f in files:
    base = os.path.basename(f)
    if base not in UNITS: continue
    k = UNITS[base]
    s = open(f, encoding="utf-8", errors="replace").read()
    geo = blocks(s, 'Geom')
    tag = "swft" if "SWFT" in base else ("raven" if "RAVEN" in base else "bd6")
    for gname, key in [("Fuselage", "fuselage"), ("Inboard Sponson", "sponson"),
                       ("Outboard Motor and Sponson Assembly", "nacelle"),
                       ("Inboard Motors", "motor")]:
        g = [b for b in geo if f'<Name>{gname}</Name>' in b]
        if not g: continue
        L = (val(g[0], 'Length') or 0) * k
        rows = sections(g[0], k)
        if len(rows) >= 2 and L > 0:
            emit(f'"{tag}_{key}"', rows, L)
print("};")
